### ISSUE TITLE
Issue with const in strict mode

### ISSUE THREAD

**Issue by thomas-kulka** [nfroidure/bufferstreams#6]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior
One of my npm dependency: gulp-ng-annotate throws an error, after bufferstreams was released to version 1.1.2. Issue:
![image](https://user-images.githubusercontent.com/20513287/33554044-72644152-d8fb-11e7-9838-ded2aa5f92f5.png)
Becasue of that I cannot deploy my application to server.

Thank you for all the help.

**Comment by nfroidure** [comment]
Looks like you are using `$ node --version v0.10.48`, This library is only tested against node 6+. You should try to revert it to a prior version but I strongly recommend you using a stable maintained NodeJS release.

**Comment by thomas-kulka** [comment]
Thank you for the quick answer.
I'll update my Node version on jenkins and chekc if that works.

**Comment by thomas-kulka** [comment]
Yes. Updating Node and npm solved the issue. 

Thanks for your help.
